spring:
  application:
    name: rag-pgvector-example

  datasource:
    #注意，如果使用阿里云的pgvector，这个url应该对应的公网地址
    url: jdbc:postgresql://drafire.pg.polardb.rds.aliyuncs.com:5432/drafire_ai_db
    username: drafire_test
    password: ${pg_password}

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      # 添加嵌入模型配置
      embedding:
        model: text-embedding-v3  # 使用通义千文的嵌入模型
        dimensions: 1024          # 与 pgvector 配置的维度一致
#      # 确保配置了正确的 rerank 模型名称
      rerank:
        options:
          model: qwen3-rerank
    vectorstore:
      pgvector:
        dimensions: 1024   #这里需要和创建的vector的维度一样
        index-type: hnsw
        distance-type: cosine_distance
        initialize-schema: true  # 开启自动建表

logging:
  level:
    com.alibaba.cloud.ai.dashscope: DEBUG
    org.springframework.web.client: DEBUG
